# config.yaml

# Problem Definition
area_bounds:
  x_min: 0
  x_max: 100
  y_min: 0
  y_max: 50
n_robots: 7
radius: 2.0

# Allocation Params
allocator_type: balanced   # greedy or balanced
start_bound_div: 5         # narrower and shorter area to spawn the robots (1: No narrowing, 10: Max narrowing)

init_tour_type: serpentine # nn or serpentine