version: '3.8'
services:
  swarm-explorer:
    build: .
    container_name: swarm-explorer
    user: "${UID}:${GID}"
    volumes:
      - ./:/app
      - ./output:/app/output
    working_dir: /app
    stdin_open: true
    tty: true