version: '3.8'
services:
  swarm-explorer:
    build: .
    container_name: swarm-explorer
    volumes:
      - ./:/ws
      - ./output:/ws/output
    working_dir: /ws
    stdin_open: true
    tty: true